
CPPFLAGS=-c -g -Iinc -Wall -Wextra -pedantic -ggdb

Work: obj/main.o obj/iStack.o obj/iList.o obj/iQueue.o
	g++ -Wall -pedantic -ggdb -o Work obj/main.o obj/iList.o obj/iStack.o obj/iQueue.o

obj/main.o: src/main.cpp inc/iList.hh inc/iStack.hh inc/iQueue.hh
	g++${CPPFLAGS} -o obj/main.cpp src/main.cpp

obj/iList.o:


obj/iStack.o:


obj/iQueue.o:
